INSERT INTO hospital
(nome, endereco, numero, complemento, bairro, cep, cidade, telefone, tipo)
VALUES
('APAE Pouso Alegre',
 'Rua Francisco Aragone',
 '15',
 NULL,
 'Árvore Grande',
 '37557-149',
 'Pouso Alegre',
 '(35)3422-6357',
 'CENTRO_REABILITACAO'),

('APAE Santa Rita',
 'Avenida Francisco Moreira Bilac Pinto',
 '229',
 NULL,
 NULL,
 '37540-000',
 'Santa Rita do Sapucaí',
 '(35)3471-2411',
 'CENTRO_REABILITACAO'),

('Hospital das Clínicas Samuel Libânio',
 'Rua Comendador José Garcia',
 '777',
 NULL,
 'Centro',
 '37550-000',
 'Pouso Alegre',
 '(35)3429-3200',
 'HOSPITAL'),

('Hemocentro Regional de Pouso Alegre',
 'Rua Comendador José Garcia',
 '846',
 NULL,
 'Centro',
 '37550-000',
 'Pouso Alegre',
 '(35)3449-9900',
 'CLINICA'),

('Hospital das Clínicas Itajubá',
 'Rua Doutor Miguel Viana',
 '420',
 NULL,
 NULL,
 '37500-080',
 'Itajubá',
 NULL,
 'HOSPITAL'),

('Hospital das Clínicas da UFMG',
 'Avenida Professor Alfredo Balena',
 '110',
 NULL,
 'Santa Efigênia',
 '30130-100',
 'Belo Horizonte',
 '(31)3307-9200',
 'HOSPITAL'),

('Hospital das Clínicas São Paulo',
 'Rua Dr. Ovídio Pires de Campos',
 '225',
 NULL,
 'Cerqueira César',
 '05403-010',
 'São Paulo',
 '(11)2661-0000',
 'HOSPITAL'),

('UNICAMP - Hospital de Clínicas',
 'Rua Vital Brasil',
 '251',
 NULL,
 'Cidade Universitária',
 '13083-888',
 'Campinas',
 '(19)3521-7000',
 'HOSPITAL'),

('Centro de Saúde Santa Rita do Sapucaí',
 'R Capitão João Antônio Dias',
 '122',
 NULL,
 'Centro',
 '37536-036',
 'Santa Rita do Sapucaí',
 NULL,
 'UBS'),

('Clínica Santa Rita Centro Médico e Diagnóstico',
 'Rua José de Almeida Paiva',
 '66',
 NULL,
 'Centro',
 '37538-044',
 'Santa Rita do Sapucaí',
 '(35)3471-1155',
 'CLINICA'),

('Banco de Olhos de Sorocaba',
 'Rua Nabek Shiroma',
 '210',
 NULL,
 NULL,
 '18031-060',
 'Sorocaba',
 '(15)3212-7000',
 'HOSPITAL'),

('CISAMESP',
 'Avenida Major Armando Rubens Storino',
 '2200',
 NULL,
 'Cidade Vergani',
 '37550-000',
 'Pouso Alegre',
 '(35)3423-3353',
 'CLINICA'),

('Medical Center Pouso Alegre',
 'Rua Coronel Brito Filho',
 '469',
 NULL,
 NULL,
 '37554-184',
 'Pouso Alegre',
 '(35)3647-3550',
 'CLINICA'),

('Sinpain Centro de Controle da Dor',
 'Rua Coronel Pedro Corrêia',
 '520',
 NULL,
 NULL,
 '37130-087',
 'Alfenas',
 '(35)3299-6414',
 'CLINICA'),

('CORPUS Pouso Alegre',
 'Avenida Coronel Alfredo Custódio de Paula',
 '255',
 NULL,
 NULL,
 '37553-063',
 'Pouso Alegre',
 '(35)3449-3350',
 'CLINICA');
 

 INSERT INTO tipo_especialidade (especialidade) VALUES
('Alergologista'),
('Cardiologia'),
('Cirurgia Geral'),
('Dermatologia'),
('Endocrinologia'),
('Endoscopia Digestiva'),
('Fisioterapia'),
('Gastroenterologia'),
('Geriatria'),
('Ginecologia'),
('Hematologia'),
('Hepatologia'),
('Infectologia'),
('Mastologia'),
('Medicina Interna/Clínica Geral'),
('Nefrologia'),
('Neurologia'),
('Neuropediatria'),
('Oftalmologia'),
('Oncologia'),
('Ortopedia/Traumatologia'),
('Pediatria'),
('Pediatria Cirúrgica'),
('Proctologia'),
('Psiquiatria'),
('Reumatologia'),
('Urologia'),
('Cirurgia Vascular');