package com.fabiana.mapa_viagem.enums;

public enum MotivoViagem {
	
	CONSULTA,
	RETORNO,
	EXAME_SANGUE,
	EXAME_URINA,
	EXAME_IMAGEM,
	EXAME_CARDIOLOGICO,
	EXAME_ENDOSCOPIA,
	PROCEDIMENTO,
	INTERNACAO,
	ALTA_HOSPITALAR,
	TRANSFERENCIA,
	TRATAMENTO_CONTINUO,
	HEMODIALISE,
	QUIMIOTERAPIA,
	RADIOTERAPIA,
	FISIOTERAPIA,
	FONOAUDIOLOGIA,
	PSICOLOGIA,
	VACINACAO,
	OFTALMOLOGISTA,
	NUTRICIONISTA,
	PERICIA_MEDICA
}
